spring:
  datasource:
    password: password
    url: jdbc:h2:dev
    username: SA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

  server:
    port: 9191